import ImagePage from "@/components/ImagePage/ImagePage";
import { WallpaperObject } from "@/components/HomePage/WallpaperCard";
import { supabase } from "@/lib/supabase";
import { notFound } from "next/navigation";
import { Metadata, ResolvingMetadata } from "next";

async function getData(imageId: string) {
  const { data, error } = await supabase
    .from("images")
    .select("id, imageUrl, prompt, created_at")
    .eq("device", "desktop")
    .eq("id", parseInt(imageId));

  if (error) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error("Failed to fetch data");
  }
  return data as WallpaperObject[];
}

type Props = {
  params: { imageId: string };
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  // read route params
  const imageId = params.imageId;
  const data = await getData(imageId);

  return {
    title: "Wallpaper #" + imageId + " | Generated by AI",
    description: "Browse free wallpapers generated by AI, powered by Leap",
    creator: "Leap",
    authors: [{ name: "Leap", url: "https://tryleap.ai" }],
    openGraph: data[0].imageUrl
      ? {
          images: [data[0].imageUrl],
        }
      : null,
    robots: {
      index: true,
    },
  };
}

export default async function Home({
  params,
}: {
  params: {
    imageId: string;
  };
}) {
  const { imageId } = params;
  const data = await getData(imageId);

  // If the image doesn't exist, return a 404 page
  if (data.length === 0) {
    notFound();
  }

  return (
    <main>
      <ImagePage wallpaper={data[0]} />
    </main>
  );
}
