import { Providers } from "./providers";

export const metadata = {
  title: "Wallpapers by AI",
  description: "Wallpapers generated by AI, powered by Leap",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
