import Navbar from "@/components/Navbar";
import { Providers } from "./providers";
import GoogleAnalytics from "@/components/GoogleAnalytics";

export const metadata = {
  title: "Wallpapers by AI",
  description: "Wallpapers generated by AI, powered by Leap",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <GoogleAnalytics />
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
